# Generated by Django 3.1.5 on 2021-01-27 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.PositiveSmallIntegerField(choices=[(1, 'Sedan'), (2, 'Jeep'), (3, 'Taxi'), (4, 'Minivan')], default=1, verbose_name='CarType')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Price')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='discount')),
            ],
            options={
                'verbose_name': 'Price list',
                'verbose_name_plural': 'Price Lists',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 15, 30, 56, 889706)),
        ),
    ]
