# Generated by Django 3.1.5 on 2021-01-27 11:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0002_auto_20210127_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='discount')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 15, 34, 55, 148310)),
        ),
        migrations.AlterField(
            model_name='prices',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwashapp.discount'),
        ),
    ]
