# Generated by Django 3.1.5 on 2021-01-27 11:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0003_auto_20210127_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='discount',
        ),
        migrations.AddField(
            model_name='discount',
            name='prices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carwashapp.prices'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 15, 48, 56, 476460)),
        ),
    ]
