# Generated by Django 3.1.5 on 2021-01-28 17:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0008_auto_20210127_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 21, 52, 22, 328144)),
        ),
        migrations.AlterField(
            model_name='prices',
            name='car_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sedan'), (2, 'Jeep'), (3, 'Taxi'), (4, 'Minivan')], default=1, unique=True, verbose_name='CarType'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.PositiveSmallIntegerField(choices=[(1, 'Sedan'), (2, 'Jeep'), (3, 'Taxi'), (4, 'Minivan')], default=1, verbose_name='CarType')),
                ('car_number', models.CharField(max_length=7)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2021, 1, 28, 21, 52, 22, 330144))),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carwashapp.branches')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='carwashapp.prices')),
                ('washer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='carwashapp.employee')),
            ],
        ),
    ]
