# Generated by Django 3.1.5 on 2021-01-28 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0011_auto_20210128_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='share_amount',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Share'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 13, 54, 865598), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 13, 54, 865598)),
        ),
    ]
