# Generated by Django 3.1.5 on 2021-01-28 18:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0013_auto_20210128_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 15, 45, 79231), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 15, 45, 79231)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='washer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carwashapp.employee'),
        ),
    ]
