# Generated by Django 3.1.5 on 2021-01-28 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0014_auto_20210128_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='price3',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='price4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 30, 24, 908528), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 30, 24, 910558)),
        ),
    ]
