# Generated by Django 3.1.5 on 2021-01-28 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0015_auto_20210128_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 39, 56, 913208), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 39, 56, 915237)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price4',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
