# Generated by Django 3.1.5 on 2021-01-28 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0016_auto_20210128_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price3',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price4',
        ),
        migrations.AddField(
            model_name='orders',
            name='washers_share',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 44, 19, 447591), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 44, 19, 448592)),
        ),
    ]
