# Generated by Django 3.1.5 on 2021-01-28 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0017_auto_20210128_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='share_amount',
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 50, 58, 901878), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 50, 58, 901878)),
        ),
    ]
