# Generated by Django 3.1.5 on 2021-01-28 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0019_auto_20210128_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 53, 44, 196389), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 53, 44, 198389)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='washers_share',
            field=models.IntegerField(default=1),
        ),
    ]
